const demoData =
  [
    {
      productId: 1,
      title: 'The Shawshank Redemption',
      year: 1994,
      director: 'Frank Darabont',
      actors: 'Tim Robbins, Morgan Freeman',
      box_office: '$28.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0111161/',
      unitPrice: 7.53,
      description: 'Released in 1994, directed by Frank Darabont. Starring Tim Robbins, Morgan Freeman. Box office collection: $28.3 M.'
    },
    {
      productId: 2,
      title: 'The Godfather',
      year: 1972,
      director: 'Francis Ford Coppola',
      actors: 'Marlon Brando, Al Pacino',
      box_office: '$246–287 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0068646/',
      unitPrice: 9.87,
      description: 'Released in 1972, directed by Francis Ford Coppola. Starring Marlon Brando, Al Pacino. Box office collection: $246–287 M.'
    },
    {
      productId: 3,
      title: 'The Dark Knight',
      year: 2008,
      director: 'Christopher Nolan',
      actors: 'Christian Bale, Heath Ledger',
      box_office: '$1.005 B',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0468569/',
      unitPrice: 14.25,
      description: 'Released in 2008, directed by Christopher Nolan. Starring Christian Bale, Heath Ledger. Box office collection: $1.005 B.'
    },
    {
      productId: 4,
      title: 'Pulp Fiction',
      year: 1994,
      director: 'Quentin Tarantino',
      actors: 'John Travolta, Uma Thurman',
      box_office: '$213.9 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0110912/',
      unitPrice: 11.34,
      description: 'Released in 1994, directed by Quentin Tarantino. Starring John Travolta, Uma Thurman. Box office collection: $213.9 M.'
    },
    {
      productId: 5,
      title: "Schindler's List",
      year: 1993,
      director: 'Steven Spielberg',
      actors: 'Liam Neeson, Ralph Fiennes',
      box_office: '$322.2 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0108052/',
      unitPrice: 8.99,
      description: 'Released in 1993, directed by Steven Spielberg. Starring Liam Neeson, Ralph Fiennes. Box office collection: $322.2 M.'
    },
    {
      productId: 6,
      title: 'The Return of the King',
      year: 2003,
      director: 'Peter Jackson',
      actors: 'Elijah Wood, Viggo Mortensen',
      box_office: '$1.142 B',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0167260/',
      unitPrice: 15.67,
      description: 'Released in 2003, directed by Peter Jackson. Starring Elijah Wood, Viggo Mortensen. Box office collection: $1.142 B.'
    },
    {
      productId: 7,
      title: 'Forrest Gump',
      year: 1994,
      director: 'Robert Zemeckis',
      actors: 'Tom Hanks, Robin Wright',
      box_office: '$678.2 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0109830/',
      unitPrice: 10.15,
      description: 'Released in 1994, directed by Robert Zemeckis. Starring Tom Hanks, Robin Wright. Box office collection: $678.2 M.'
    },
    {
      productId: 8,
      title: 'Inception',
      year: 2010,
      director: 'Christopher Nolan',
      actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt',
      box_office: '$836.8 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt1375666/',
      unitPrice: 13.49,
      description: 'Released in 2010, directed by Christopher Nolan. Starring Leonardo DiCaprio, Joseph Gordon-Levitt. Box office collection: $836.8 M.'
    },
    {
      productId: 9,
      title: 'Fight Club',
      year: 1999,
      director: 'David Fincher',
      actors: 'Brad Pitt, Edward Norton',
      box_office: '$101.2 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0137523/',
      unitPrice: 6.78,
      description: 'Released in 1999, directed by David Fincher. Starring Brad Pitt, Edward Norton. Box office collection: $101.2 M.'
    },
    {
      productId: 10,
      title: 'The Matrix',
      year: 1999,
      director: 'Lana Wachowski, Lilly Wachowski',
      actors: 'Keanu Reeves, Laurence Fishburne',
      box_office: '$465.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0133093/',
      unitPrice: 16.23,
      description: 'Released in 1999, directed by Lana Wachowski and Lilly Wachowski. Starring Keanu Reeves, Laurence Fishburne. Box office collection: $465.3 M.'
    },
    {
      productId: 11,
      title: 'Goodfellas',
      year: 1990,
      director: 'Martin Scorsese',
      actors: 'Robert De Niro, Ray Liotta',
      box_office: '$46.8 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0099685/',
      unitPrice: 12.88,
      description: 'Released in 1990, directed by Martin Scorsese. Starring Robert De Niro, Ray Liotta. Box office collection: $46.8 M.'
    },
    {
      productId: 12,
      title: 'The Silence of the Lambs',
      year: 1991,
      director: 'Jonathan Demme',
      actors: 'Jodie Foster, Anthony Hopkins',
      box_office: '$272.7 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0102926/',
      unitPrice: 7.99,
      description: 'Released in 1991, directed by Jonathan Demme. Starring Jodie Foster, Anthony Hopkins. Box office collection: $272.7 M.'
    },
    {
      productId: 13,
      title: 'Se7en',
      year: 1995,
      director: 'David Fincher',
      actors: 'Morgan Freeman, Brad Pitt',
      box_office: '$327.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjODdhMDU5NDM1XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0114369/',
      unitPrice: 9.54,
      description: 'Released in 1995, directed by David Fincher. Starring Morgan Freeman, Brad Pitt. Box office collection: $327.3 M.'
    },
    {
      productId: 14,
      title: 'City of God',
      year: 2002,
      director: 'Fernando Meirelles',
      actors: 'Alexandre Rodrigues, Leandro Firmino',
      box_office: '$30.6 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0317248/',
      unitPrice: 11.05,
      description: 'Released in 2002, directed by Fernando Meirelles. Starring Alexandre Rodrigues, Leandro Firmino. Box office collection: $30.6 M.'
    },
    {
      productId: 15,
      title: 'The Usual Suspects',
      year: 1995,
      director: 'Bryan Singer',
      actors: 'Kevin Spacey, Gabriel Byrne',
      box_office: '$34.4 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BOTE5MDUxZDUtZWZmZC00NDVmLWFhOGQtNWI2YTc4NzY3MGQ0XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0114814/',
      unitPrice: 8.75,
      description: 'Released in 1995, directed by Bryan Singer. Starring Kevin Spacey, Gabriel Byrne. Box office collection: $34.4 M.'
    },
    {
      productId: 16,
      title: 'Saving Private Ryan',
      year: 1998,
      director: 'Steven Spielberg',
      actors: 'Tom Hanks, Matt Damon',
      box_office: '$482.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0120815/',
      unitPrice: 16,
      description: 'Released in 1998, directed by Steven Spielberg. Starring Tom Hanks, Matt Damon. Box office collection: $482.3 M.'
    },
    {
      productId: 17,
      title: 'Spirited Away',
      year: 2001,
      director: 'Hayao Miyazaki',
      actors: 'Rumi Hiiragi, Miyu Irino',
      box_office: '$347.7 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0245429/',
      unitPrice: 5.45,
      description: 'Released in 2001, directed by Hayao Miyazaki. Starring Rumi Hiiragi, Miyu Irino. Box office collection: $347.7 M.'
    },
    {
      productId: 18,
      title: 'Life Is Beautiful',
      year: 1997,
      director: 'Roberto Benigni',
      actors: 'Roberto Benigni, Nicoletta Braschi',
      box_office: '$230.1 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZTBhOGYzZjQtYzE0Mi00MGIwLWE0MWYtNzMxNTM2OTFkM2NjXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0118799/',
      unitPrice: 14.19,
      description: 'Released in 1997, directed by Roberto Benigni. Starring Roberto Benigni, Nicoletta Braschi. Box office collection: $230.1 M.'
    },
    {
      productId: 19,
      title: 'Interstellar',
      year: 2014,
      director: 'Christopher Nolan',
      actors: 'Matthew McConaughey, Anne Hathaway',
      box_office: '$701.8 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0816692/',
      unitPrice: 12.01,
      description: 'Released in 2014, directed by Christopher Nolan. Starring Matthew McConaughey, Anne Hathaway. Box office collection: $701.8 M.'
    },
    {
      productId: 20,
      title: 'The Green Mile',
      year: 1999,
      director: 'Frank Darabont',
      actors: 'Tom Hanks, Michael Clarke Duncan',
      box_office: '$286.8 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0120689/',
      unitPrice: 10.99,
      description: 'Released in 1999, directed by Frank Darabont. Starring Tom Hanks, Michael Clarke Duncan. Box office collection: $286.8 M.'
    },
    {
      productId: 21,
      title: 'The Lion King',
      year: 1994,
      director: 'Roger Allers, Rob Minkoff',
      actors: 'Matthew Broderick, Jeremy Irons',
      box_office: '$968.5 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZGRiZDZhZjItM2M3ZC00Y2IyLTk3Y2MtMWY5YjliNDFkZTJlXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0110357/',
      unitPrice: 15.49,
      description: 'Released in 1994, directed by Roger Allers and Rob Minkoff. Starring Matthew Broderick, Jeremy Irons. Box office collection: $968.5 M.'
    },
    {
      productId: 22,
      title: 'The Departed',
      year: 2006,
      director: 'Martin Scorsese',
      actors: 'Leonardo DiCaprio, Matt Damon',
      box_office: '$291.5 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0407887/',
      unitPrice: 7.65,
      description: 'Released in 2006, directed by Martin Scorsese. Starring Leonardo DiCaprio, Matt Damon. Box office collection: $291.5 M.'
    },
    {
      productId: 23,
      title: 'Back to the Future',
      year: 1985,
      director: 'Robert Zemeckis',
      actors: 'Michael J. Fox, Christopher Lloyd',
      box_office: '$388.8 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZmM3ZjE0NzctNjBiOC00MDZmLTgzMTUtNGVlOWFlOTNiZDJiXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0088763/',
      unitPrice: 9.99,
      description: 'Released in 1985, directed by Robert Zemeckis. Starring Michael J. Fox, Christopher Lloyd. Box office collection: $388.8 M.'
    },
    {
      productId: 24,
      title: 'Terminator 2: Judgment Day',
      year: 1991,
      director: 'James Cameron',
      actors: 'Arnold Schwarzenegger, Linda Hamilton',
      box_office: '$520.9 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNGMyMGNkMDUtMjc2Ni00NWFlLTgyODEtZTY2MzBiZTg0OWZiXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0103064/',
      unitPrice: 17,
      description: 'Released in 1991, directed by James Cameron. Starring Arnold Schwarzenegger, Linda Hamilton. Box office collection: $520.9 M.'
    },
    {
      productId: 25,
      title: 'American History X',
      year: 1998,
      director: 'Tony Kaye',
      actors: 'Edward Norton, Edward Furlong',
      box_office: '$23.9 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMzhiOTQ0NDItOTg0Zi00OGVmLWE0OGEtMTI4NDM0NWMxZWU4XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0120586/',
      unitPrice: 13.5,
      description: 'Released in 1998, directed by Tony Kaye. Starring Edward Norton, Edward Furlong. Box office collection: $23.9 M.'
    },
    {
      productId: 26,
      title: 'Whiplash',
      year: 2014,
      director: 'Damien Chazelle',
      actors: 'Miles Teller, J.K. Simmons',
      box_office: '$49.0 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMDFjOWFkYzktYzhhMC00NmYyLTkwY2EtYjViMDhmNzg0OGFkXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt2582802/',
      unitPrice: 6.25,
      description: 'Released in 2014, directed by Damien Chazelle. Starring Miles Teller, J.K. Simmons. Box office collection: $49.0 M.'
    },
    {
      productId: 27,
      title: 'The Prestige',
      year: 2006,
      director: 'Christopher Nolan',
      actors: 'Christian Bale, Hugh Jackman',
      box_office: '$109.7 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0482571/',
      unitPrice: 8.65,
      description: 'Released in 2006, directed by Christopher Nolan. Starring Christian Bale, Hugh Jackman. Box office collection: $109.7 M.'
    },
    {
      productId: 28,
      title: 'Gladiator',
      year: 2000,
      director: 'Ridley Scott',
      actors: 'Russell Crowe, Joaquin Phoenix',
      box_office: '$460.5 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0172495/',
      unitPrice: 16.8,
      description: 'Released in 2000, directed by Ridley Scott. Starring Russell Crowe, Joaquin Phoenix. Box office collection: $460.5 M.'
    },
    {
      productId: 29,
      title: 'Django Unchained',
      year: 2012,
      director: 'Quentin Tarantino',
      actors: 'Jamie Foxx, Christoph Waltz',
      box_office: '$425.4 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt1853728/',
      unitPrice: 11.11,
      description: 'Released in 2012, directed by Quentin Tarantino. Starring Jamie Foxx, Christoph Waltz. Box office collection: $425.4 M.'
    },
    {
      productId: 30,
      title: 'Memento',
      year: 2000,
      director: 'Christopher Nolan',
      actors: 'Guy Pearce, Carrie-Anne Moss',
      box_office: '$39.7 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BYmQ3MjliNjAtNWFiZS00YWI1LTlmZTktMzBiNDE1NjRhZjU0XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0209144/',
      unitPrice: 14.89,
      description: 'Released in 2000, directed by Christopher Nolan. Starring Guy Pearce, Carrie-Anne Moss. Box office collection: $39.7 M.'
    },
    {
      productId: 31,
      title: 'Casablanca',
      year: 1942,
      director: 'Michael Curtiz',
      actors: 'Humphrey Bogart, Ingrid Bergman',
      box_office: '$1.0 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNWEzN2U1YTYtYTQyMS00NTVkLWE2NGQtZWFlMmM0MDNjMmRiXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0034583/',
      unitPrice: 9.15,
      description: 'Released in 1942, directed by Michael Curtiz. Starring Humphrey Bogart, Ingrid Bergman. Box office collection: $1.0 M.'
    },
    {
      productId: 32,
      title: 'Rear Window',
      year: 1954,
      director: 'Alfred Hitchcock',
      actors: 'James Stewart, Grace Kelly',
      box_office: '$3.5 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BODZhOWI1ODgtMzdiOS00YjNkLTgwOGUtYmIyZDg5ZmQwMzQ1XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0047396/',
      unitPrice: 13.67,
      description: 'Released in 1954, directed by Alfred Hitchcock. Starring James Stewart, Grace Kelly. Box office collection: $3.5 M.'
    },
    {
      productId: 33,
      title: 'Once Upon a Time in the West',
      year: 1968,
      director: 'Sergio Leone',
      actors: 'Henry Fonda, Charles Bronson',
      box_office: '$5.5 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZjYyNGY1MDEtN2I1MC00MGVhLTljZTYtODQ1NzQ0ODc2NzZlXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0064116/',
      unitPrice: 10.25,
      description: 'Released in 1968, directed by Sergio Leone. Starring Henry Fonda, Charles Bronson. Box office collection: $5.5 M.'
    },
    {
      productId: 34,
      title: 'Apocalypse Now',
      year: 1979,
      director: 'Francis Ford Coppola',
      actors: 'Martin Sheen, Marlon Brando',
      box_office: '$150.0 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZDhiMTljYjYtODc1Yy00MmEwLTg2OTYtYmE1YTRmNDE4MmEwXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0078788/',
      unitPrice: 12.34,
      description: 'Released in 1979, directed by Francis Ford Coppola. Starring Martin Sheen, Marlon Brando. Box office collection: $150.0 M.'
    },
    {
      productId: 35,
      title: 'Alien',
      year: 1979,
      director: 'Ridley Scott',
      actors: 'Sigourney Weaver, Tom Skerritt',
      box_office: '$104.9 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BN2NhMDk2MmEtZDQzOC00MmY5LThhYzAtMDdjZGFjOGZjMjdjXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0078748/',
      unitPrice: 7.77,
      description: 'Released in 1979, directed by Ridley Scott. Starring Sigourney Weaver, Tom Skerritt. Box office collection: $104.9 M.'
    },
    {
      productId: 36,
      title: 'City Lights',
      year: 1931,
      director: 'Charlie Chaplin',
      actors: 'Charlie Chaplin, Virginia Cherrill',
      box_office: '$3.0 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BM2U4NjgzODUtODkyOC00YTE2LTlhNTItYzFlYmM1NTEzZDA2XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0021749/',
      unitPrice: 15.22,
      description: 'Released in 1931, directed by Charlie Chaplin. Starring Charlie Chaplin, Virginia Cherrill. Box office collection: $3.0 M.'
    },
    {
      productId: 37,
      title: 'Modern Times',
      year: 1936,
      director: 'Charlie Chaplin',
      actors: 'Charlie Chaplin, Paulette Goddard',
      box_office: '$1.2 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BODVkZGFhNGQtYjdiYi00Njc4LWFmYTItNTlmNzJjMTg1ZDc5XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0027977/',
      unitPrice: 8.99,
      description: 'Released in 1936, directed by Charlie Chaplin. Starring Charlie Chaplin, Paulette Goddard. Box office collection: $1.2 M.'
    },
    {
      productId: 38,
      title: 'Psycho',
      year: 1960,
      director: 'Alfred Hitchcock',
      actors: 'Anthony Perkins, Janet Leigh',
      box_office: '$32.0 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BYjZhMzFiZjItODA3ZC00MmRhLWIzMGYtMmVjOWUwYTA3MTRjXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0054215/',
      unitPrice: 10.78,
      description: 'Released in 1960, directed by Alfred Hitchcock. Starring Anthony Perkins, Janet Leigh. Box office collection: $32.0 M.'
    },
    {
      productId: 39,
      title: 'North by Northwest',
      year: 1959,
      director: 'Alfred Hitchcock',
      actors: 'Cary Grant, Eva Marie Saint',
      box_office: '$7.4 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZWIzODI2OGItMzM0Ny00OGRmLTlkNmItMDQxMTFmMTk3YmQwXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0053125/',
      unitPrice: 11.34,
      description: 'Released in 1959, directed by Alfred Hitchcock. Starring Cary Grant, Eva Marie Saint. Box office collection: $7.4 M.'
    },
    {
      productId: 40,
      title: 'Vertigo',
      year: 1958,
      director: 'Alfred Hitchcock',
      actors: 'James Stewart, Kim Novak',
      box_office: '$7.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNzEyZTUxMWItMGVhYy00Y2NlLTljYTMtYzBmMzI1YmUyMDBkXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0052357/',
      unitPrice: 16.11,
      description: 'Released in 1958, directed by Alfred Hitchcock. Starring James Stewart, Kim Novak. Box office collection: $7.3 M.'
    },
    {
      productId: 41,
      title: 'Raiders of the Lost Ark',
      year: 1981,
      director: 'Steven Spielberg',
      actors: 'Harrison Ford, Karen Allen',
      box_office: '$389.9 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BOGNhMjg2ZjgtYzk4Ni00MTViLTg1MmUtYzM2MDZiYjZlMmU3XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0082971/',
      unitPrice: 14.5,
      description: 'Released in 1981, directed by Steven Spielberg. Starring Harrison Ford, Karen Allen. Box office collection: $389.9 M.'
    },
    {
      productId: 42,
      title: 'The Shining',
      year: 1980,
      director: 'Stanley Kubrick',
      actors: 'Jack Nicholson, Shelley Duvall',
      box_office: '$44.0 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0081505/',
      unitPrice: 7.45,
      description: 'Released in 1980, directed by Stanley Kubrick. Starring Jack Nicholson, Shelley Duvall. Box office collection: $44.0 M.'
    },
    {
      productId: 43,
      title: 'Aliens',
      year: 1986,
      director: 'James Cameron',
      actors: 'Sigourney Weaver, Michael Biehn',
      box_office: '$131.1 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZjIyNGJhYzYtN2I1My00OTVhLWEyMzItZTVjNDMzOTVkYWViXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0090605/',
      unitPrice: 9.99,
      description: 'Released in 1986, directed by James Cameron. Starring Sigourney Weaver, Michael Biehn. Box office collection: $131.1 M.'
    },
    {
      productId: 44,
      title: 'Braveheart',
      year: 1995,
      director: 'Mel Gibson',
      actors: 'Mel Gibson, Sophie Marceau',
      box_office: '$210.4 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNGMxZDBhNGQtYTZlNi00N2UzLWI4NDEtNmUzNWM2NTdmZDA0XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0112573/',
      unitPrice: 12.88,
      description: 'Released in 1995, directed by Mel Gibson. Starring Mel Gibson, Sophie Marceau. Box office collection: $210.4 M.'
    },
    {
      productId: 45,
      title: 'Titanic',
      year: 1997,
      director: 'James Cameron',
      actors: 'Leonardo DiCaprio, Kate Winslet',
      box_office: '$2.195 B',
      image_url: 'https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0120338/',
      unitPrice: 10.49,
      description: 'Released in 1997, directed by James Cameron. Starring Leonardo DiCaprio, Kate Winslet. Box office collection: $2.195 B.'
    },
    {
      productId: 46,
      title: 'Avatar',
      year: 2009,
      director: 'James Cameron',
      actors: 'Sam Worthington, Zoe Saldana',
      box_office: '$2.923 B',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMDEzMmQwZjctZWU2My00MWNlLWE0NjItMDJlYTRlNGJiZjcyXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0499549/',
      unitPrice: 8.66,
      description: 'Released in 2009, directed by James Cameron. Starring Sam Worthington, Zoe Saldana. Box office collection: $2.923 B.'
    },
    {
      productId: 47,
      title: 'The Dark Knight Rises',
      year: 2012,
      director: 'Christopher Nolan',
      actors: 'Christian Bale, Tom Hardy',
      box_office: '$1.081 B',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt1345836/',
      unitPrice: 15.99,
      description: 'Released in 2012, directed by Christopher Nolan. Starring Christian Bale, Tom Hardy. Box office collection: $1.081 B.'
    },
    {
      productId: 48,
      title: 'The Avengers',
      year: 2012,
      director: 'Joss Whedon',
      actors: 'Robert Downey Jr., Chris Evans',
      box_office: '$1.519 B',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0848228/',
      unitPrice: 11.45,
      description: 'Released in 2012, directed by Joss Whedon. Starring Robert Downey Jr., Chris Evans. Box office collection: $1.519 B.'
    },
    {
      productId: 49,
      title: 'Jurassic Park',
      year: 1993,
      director: 'Steven Spielberg',
      actors: 'Sam Neill, Laura Dern',
      box_office: '$1.034 B',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0107290/',
      unitPrice: 6.99,
      description: 'Released in 1993, directed by Steven Spielberg. Starring Sam Neill, Laura Dern. Box office collection: $1.034 B.'
    },
    {
      productId: 50,
      title: 'Star Wars: A New Hope',
      year: 1977,
      director: 'George Lucas',
      actors: 'Mark Hamill, Harrison Ford',
      box_office: '$775.4 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BOGUwMDk0Y2MtNjBlNi00NmRiLTk2MWYtMGMyMDlhYmI4ZDBjXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0076759/',
      unitPrice: 14.99,
      description: 'Released in 1977, directed by George Lucas. Starring Mark Hamill, Harrison Ford. Box office collection: $775.4 M.'
    },
    {
      productId: 51,
      title: 'The Empire Strikes Back',
      year: 1980,
      director: 'Irvin Kershner',
      actors: 'Mark Hamill, Harrison Ford',
      box_office: '$538.4 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMTkxNGFlNDktZmJkNC00MDdhLTg0MTEtZjZiYWI3MGE5NWIwXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0080684/',
      unitPrice: 10.35,
      description: 'Released in 1980, directed by Irvin Kershner. Starring Mark Hamill, Harrison Ford. Box office collection: $538.4 M.'
    },
    {
      productId: 52,
      title: 'Return of the Jedi',
      year: 1983,
      director: 'Richard Marquand',
      actors: 'Mark Hamill, Harrison Ford',
      box_office: '$572.7 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNWEwOTI0MmUtMGNmNy00ODViLTlkZDQtZTg1YmQ3MDgyNTUzXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0086190/',
      unitPrice: 13.45,
      description: 'Released in 1983, directed by Richard Marquand. Starring Mark Hamill, Harrison Ford. Box office collection: $572.7 M.'
    },
    {
      productId: 53,
      title: 'Toy Story',
      year: 1995,
      director: 'John Lasseter',
      actors: 'Tom Hanks, Tim Allen',
      box_office: '$373.6 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0114709/',
      unitPrice: 9.75,
      description: 'Released in 1995, directed by John Lasseter. Starring Tom Hanks, Tim Allen. Box office collection: $373.6 M.'
    },
    {
      productId: 54,
      title: 'Up',
      year: 2009,
      director: 'Pete Docter',
      actors: 'Ed Asner, Jordan Nagai',
      box_office: '$735.1 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNmI1ZTc5MWMtMDYyOS00ZDc2LTkzOTAtNjQ4NWIxNjYyNDgzXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt1049413/',
      unitPrice: 16.89,
      description: 'Released in 2009, directed by Pete Docter. Starring Ed Asner, Jordan Nagai. Box office collection: $735.1 M.'
    },
    {
      productId: 55,
      title: 'Finding Nemo',
      year: 2003,
      director: 'Andrew Stanton',
      actors: 'Albert Brooks, Ellen DeGeneres',
      box_office: '$940.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMTc5NjExNTA5OV5BMl5BanBnXkFtZTYwMTQ0ODY2._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0266543/',
      unitPrice: 7.99,
      description: 'Released in 2003, directed by Andrew Stanton. Starring Albert Brooks, Ellen DeGeneres. Box office collection: $940.3 M.'
    },
    {
      productId: 56,
      title: 'WALL·E',
      year: 2008,
      director: 'Andrew Stanton',
      actors: 'Ben Burtt, Elissa Knight',
      box_office: '$533.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0910970/',
      unitPrice: 11.33,
      description: 'Released in 2008, directed by Andrew Stanton. Starring Ben Burtt, Elissa Knight. Box office collection: $533.3 M.'
    },
    {
      productId: 57,
      title: 'Coco',
      year: 2017,
      director: 'Lee Unkrich',
      actors: 'Anthony Gonzalez, Gael García Bernal',
      box_office: '$807.1 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMDIyM2E2NTAtMzlhNy00ZGUxLWI1NjgtZDY5MzhiMDc5NGU3XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt2380307/',
      unitPrice: 15.5,
      description: 'Released in 2017, directed by Lee Unkrich. Starring Anthony Gonzalez, Gael García Bernal. Box office collection: $807.1 M.'
    },
    {
      productId: 58,
      title: "Pan's Labyrinth",
      year: 2006,
      director: 'Guillermo del Toro',
      actors: 'Ivana Baquero, Sergi López',
      box_office: '$83.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BOTc1NTAxMWItMWFlNy00MmU2LTkwMTMtNzMwOTg5OTQ5YTFiXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0457430/',
      unitPrice: 8.45,
      description: 'Released in 2006, directed by Guillermo del Toro. Starring Ivana Baquero, Sergi López. Box office collection: $83.3 M.'
    },
    {
      productId: 59,
      title: 'Her',
      year: 2013,
      director: 'Spike Jonze',
      actors: 'Joaquin Phoenix, Scarlett Johansson',
      box_office: '$47.4 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt1798709/',
      unitPrice: 10.89,
      description: 'Released in 2013, directed by Spike Jonze. Starring Joaquin Phoenix, Scarlett Johansson. Box office collection: $47.4 M.'
    },
    {
      productId: 60,
      title: 'Eternal Sunshine of the Spotless Mind',
      year: 2004,
      director: 'Michel Gondry',
      actors: 'Jim Carrey, Kate Winslet',
      box_office: '$72.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0338013/',
      unitPrice: 12.5,
      description: 'Released in 2004, directed by Michel Gondry. Starring Jim Carrey, Kate Winslet. Box office collection: $72.3 M.'
    },
    {
      productId: 61,
      title: 'No Country for Old Men',
      year: 2007,
      director: 'Joel & Ethan Coen',
      actors: 'Tommy Lee Jones, Javier Bardem',
      box_office: '$171.6 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0477348/',
      unitPrice: 7.49,
      description: 'Released in 2007, directed by Joel & Ethan Coen. Starring Tommy Lee Jones, Javier Bardem. Box office collection: $171.6 M.'
    },
    {
      productId: 62,
      title: 'There Will Be Blood',
      year: 2007,
      director: 'Paul Thomas Anderson',
      actors: 'Daniel Day-Lewis, Paul Dano',
      box_office: '$76.2 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0469494/',
      unitPrice: 14.67,
      description: 'Released in 2007, directed by Paul Thomas Anderson. Starring Daniel Day-Lewis, Paul Dano. Box office collection: $76.2 M.'
    },
    {
      productId: 63,
      title: 'The Grand Budapest Hotel',
      year: 2014,
      director: 'Wes Anderson',
      actors: 'Ralph Fiennes, F. Murray Abraham',
      box_office: '$174.8 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt2278388/',
      unitPrice: 9.99,
      description: 'Released in 2014, directed by Wes Anderson. Starring Ralph Fiennes, F. Murray Abraham. Box office collection: $174.8 M.'
    },
    {
      productId: 64,
      title: 'The Wolf of Wall Street',
      year: 2013,
      director: 'Martin Scorsese',
      actors: 'Leonardo DiCaprio, Jonah Hill',
      box_office: '$392.0 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0993846/',
      unitPrice: 16.25,
      description: 'Released in 2013, directed by Martin Scorsese. Starring Leonardo DiCaprio, Jonah Hill. Box office collection: $392.0 M.'
    },
    {
      productId: 65,
      title: 'In Bruges',
      year: 2008,
      director: 'Martin McDonagh',
      actors: 'Colin Farrell, Brendan Gleeson',
      box_office: '$34.1 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZmQ5ZjZlMzMtODA1ZS00NTNiLWIzOTYtOTQyYjQ2YWQxMTA1XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt0783233/',
      unitPrice: 11.22,
      description: 'Released in 2008, directed by Martin McDonagh. Starring Colin Farrell, Brendan Gleeson. Box office collection: $34.1 M.'
    },
    {
      productId: 66,
      title: 'Moonlight',
      year: 2016,
      director: 'Barry Jenkins',
      actors: 'Mahershala Ali, Alex Hibbert',
      box_office: '$65.3 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt4975722/',
      unitPrice: 8.99,
      description: 'Released in 2016, directed by Barry Jenkins. Starring Mahershala Ali, Alex Hibbert. Box office collection: $65.3 M.'
    },
    {
      productId: 67,
      title: 'Parasite',
      year: 2019,
      director: 'Bong Joon-ho',
      actors: 'Song Kang-ho, Lee Sun-kyun',
      box_office: '$258.8 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt6751668/',
      unitPrice: 12.1,
      description: 'Released in 2019, directed by Bong Joon-ho. Starring Song Kang-ho, Lee Sun-kyun. Box office collection: $258.8 M.'
    },
    {
      productId: 68,
      title: 'Get Out',
      year: 2017,
      director: 'Jordan Peele',
      actors: 'Daniel Kaluuya, Allison Williams',
      box_office: '$255.4 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt5052448/',
      unitPrice: 10.05,
      description: 'Released in 2017, directed by Jordan Peele. Starring Daniel Kaluuya, Allison Williams. Box office collection: $255.4 M.'
    },
    {
      productId: 69,
      title: 'Mad Max: Fury Road',
      year: 2015,
      director: 'George Miller',
      actors: 'Tom Hardy, Charlize Theron',
      box_office: '$374.7 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZDRkODJhOTgtOTc1OC00NTgzLTk4NjItNDgxZDY4YjlmNDY2XkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt1392190/',
      unitPrice: 15.2,
      description: 'Released in 2015, directed by George Miller. Starring Tom Hardy, Charlize Theron. Box office collection: $374.7 M.'
    },
    {
      productId: 70,
      title: 'The Social Network',
      year: 2010,
      director: 'David Fincher',
      actors: 'Jesse Eisenberg, Andrew Garfield',
      box_office: '$224.9 M',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMjlkNTE5ZTUtNGEwNy00MGVhLThmZjMtZjU1NDE5Zjk1NDZkXkEyXkFqcGc@._V1_SX300.jpg',
      imdb_url: 'https://www.imdb.com/title/tt1285016/',
      unitPrice: 13.75,
      description: 'Released in 2010, directed by David Fincher. Starring Jesse Eisenberg, Andrew Garfield. Box office collection: $224.9 M.'
    }
  ];

const OrderStatuses = [
  {
    statusId: 1,
    title: "PENDING",
  },
  {
    statusId: 2,
    title: "CONFIRMED",
  },
];
export { OrderStatuses };
export default demoData;
